window.BILLING_APP_CONFIG = {
  bootstrapUrl: "./data/current-workbook.json",
  workbookReadUrl: "./data/current-workbook.json",
  workbookWriteUrl: "",
  workbookHistoryWriteBaseUrl: "",
  invoiceDraftUrl: "",
  invoiceArtifactWriteBaseUrl: "",
  privateInvoiceLinkWriteBaseUrl: "",
  privateInvoiceLinkReadBaseUrl: "",
  automationOutboxUrl: "",
  checkerWebhookUrl: "",
  lookerImportWebhookUrl: "",
  contractParseWebhookUrl: "",
  contractExtractWebhookUrl: "",
  enableSharedWorkbook: true,
  enableRemoteInvoiceReads: false,
  enableInvoiceArtifacts: false,
  enablePrivateInvoiceLinks: false,
  enableCheckerRuns: false,
  enableLookerImports: false,
  enableContractAutomation: false
};
