window.BILLING_APP_CONFIG = {
  authMethod: "",
  awsRegion: "",
  cognitoUserPoolId: "",
  cognitoUserPoolClientId: "",
  cognitoIdentityPoolId: "",
  cognitoHostedUiDomain: "",
  cognitoRedirectUrl: "",
  cognitoScopes: "openid email profile",
  bootstrapUrl: "./data/current-workbook.json",
  workbookReadUrl: "./data/current-workbook.json",
  workbookWriteUrl: "",
  workbookHistoryWriteBaseUrl: "",
  invoiceDraftUrl: "",
  invoiceArtifactWriteBaseUrl: "",
  privateInvoiceLinkSignerUrl: "",
  privateInvoiceLinkWriteBaseUrl: "",
  privateInvoiceLinkReadBaseUrl: "",
  automationOutboxUrl: "",
  checkerWebhookUrl: "",
  lookerImportWebhookUrl: "",
  contractParseWebhookUrl: "",
  contractExtractWebhookUrl: "",
  enableSharedWorkbook: true,
  enableRemoteInvoiceReads: false,
  enableInvoiceArtifacts: false,
  enablePrivateInvoiceLinks: false,
  enableCheckerRuns: false,
  enableLookerImports: false,
  enableContractAutomation: false
};
