export const billingAppConfig = {
  mode: "frontend-static",
  workspaceLabel: "Veem Billing Workspace",
  adminUsername: "VeemAdmin",
  adminPassword: "",
  authMethod: "",
  awsRegion: "",
  cognitoUserPoolId: "",
  cognitoUserPoolClientId: "",
  cognitoIdentityPoolId: "",
  cognitoHostedUiDomain: "",
  cognitoRedirectUrl: "",
  cognitoScopes: "openid email profile",
  bootstrapUrl: "./data/current-workbook.json",
  workbookReadUrl: "",
  workbookWriteUrl: "",
  workbookHistoryWriteBaseUrl: "",
  invoiceDraftUrl: "",
  invoiceArtifactWriteBaseUrl: "",
  privateInvoiceLinkSignerUrl: "",
  privateInvoiceLinkWriteBaseUrl: "",
  privateInvoiceLinkReadBaseUrl: "",
  automationOutboxUrl: "",
  lookerImportWebhookUrl: "",
  contractParseWebhookUrl: "",
  contractExtractWebhookUrl: "",
  enableSharedWorkbook: true,
  enableRemoteInvoiceReads: false,
  enableInvoiceArtifacts: false,
  enablePrivateInvoiceLinks: false,
  enableLookerImports: false,
  enableContractAutomation: false
};
