export const billingAppConfig = {
  mode: "frontend-static",
  workspaceLabel: "Veem Billing Workspace",
  bootstrapUrl: "./data/current-workbook.json",
  workbookReadUrl: "",
  workbookWriteUrl: "",
  workbookHistoryWriteBaseUrl: "",
  invoiceDraftUrl: "",
  invoiceArtifactWriteBaseUrl: "",
  privateInvoiceLinkWriteBaseUrl: "",
  privateInvoiceLinkReadBaseUrl: "",
  automationOutboxUrl: "",
  checkerWebhookUrl: "",
  lookerImportWebhookUrl: "",
  contractParseWebhookUrl: "",
  contractExtractWebhookUrl: "",
  enableSharedWorkbook: true,
  enableRemoteInvoiceReads: false,
  enableInvoiceArtifacts: false,
  enablePrivateInvoiceLinks: false,
  enableCheckerRuns: false,
  enableLookerImports: false,
  enableContractAutomation: false
};
