import fs from "node:fs";
import path from "node:path";

const ROOT_DIR = "/Users/danielsinukoff/Documents/billing-workbook";
const RUNTIME_PATH = path.join(ROOT_DIR, "tools", "looker_sync_runtime.mjs");
const CONFIG_PATH = path.join(ROOT_DIR, "docs", "looker-direct-reports.json");
const OUTPUT_PATH = path.join(ROOT_DIR, "docs", "n8n-looker-cloud.workflow.json");

const DEFAULT_BUCKET = "veem-prod-virginia-poc-billing-fe-delete-me";
const DEFAULT_WORKBOOK_KEY = "partner-billing-form/data/current-workbook.json";
const DEFAULT_SUMMARY_KEY = "partner-billing-form/data/looker-sync/latest-summary.json";
const DEFAULT_WORKBOOK_HISTORY_PREFIX = "partner-billing-form/data/history/workbook";

function stripExports(source) {
  return source.replace(/^export\s+/gm, "");
}

function splitS3Key(key) {
  const normalized = String(key || "").replace(/^\/+|\/+$/g, "");
  const parts = normalized.split("/");
  const fileName = parts.pop() || "artifact.json";
  return {
    parentFolderKey: parts.join("/"),
    fileName,
  };
}

function buildContextCode(config) {
  const reports = (config.reports || []).map((report) => ({
    fileType: report.fileType,
    fileName: report.fileName,
    lookId: report.lookId,
    reportName: report.reportName,
    reportTimeout: report.reportTimeout || 600,
    historyWindowDays: report.historyWindowDays || 0,
    historyFilterKey: report.historyFilterKey || "",
    periodFilterKey: report.periodFilterKey || "",
    periodFilterMode: report.periodFilterMode || "",
  }));

  return [
    "const now = new Date();",
    "const period = `${now.getUTCFullYear()}-${String(now.getUTCMonth() + 1).padStart(2, \"0\")}`;",
    "const timestamp = now.toISOString().replace(/[-:.TZ]/g, \"\").slice(0, 14);",
    "const runToken = Math.random().toString(16).slice(2, 8);",
    "const reports = " + JSON.stringify(reports, null, 2) + ";",
    "return [{ json: {",
    "  period,",
    "  runId: `n8n-${timestamp}-${runToken}-${period.replace(\"-\", \"\")}`,",
    `  bucketName: ${JSON.stringify(DEFAULT_BUCKET)},`,
    `  workbookKey: ${JSON.stringify(DEFAULT_WORKBOOK_KEY)},`,
    `  summaryKey: ${JSON.stringify(DEFAULT_SUMMARY_KEY)},`,
    `  workbookHistoryPrefix: ${JSON.stringify(DEFAULT_WORKBOOK_HISTORY_PREFIX)},`,
    `  lookerBaseUrl: ${JSON.stringify(config.baseUrl || "")},`,
    `  lookerApiVersion: ${JSON.stringify(config.apiVersion || "4.0")},`,
    `  forceProduction: ${JSON.stringify(Boolean(config.forceProduction))},`,
    "  lookerClientId: \"SET_LOOKER_CLIENT_ID\",",
    "  lookerClientSecret: \"SET_LOOKER_CLIENT_SECRET\",",
    "  reports",
    "} }];",
  ].join("\n");
}

function buildSyncCode(runtimeSource) {
  return [
    "const input = $input.first();",
    "const ctx = input.json || {};",
    "const workbookBinary = input.binary?.currentWorkbook?.data || \"\";",
    "let workbookPayload = { workspace: { label: \"Veem Billing Workspace\" }, user: {}, snapshot: {} };",
    "if (workbookBinary) {",
    "  try {",
    "    workbookPayload = JSON.parse(Buffer.from(workbookBinary, \"base64\").toString(\"utf8\"));",
    "  } catch (error) {",
    "    throw new Error(`Current workbook JSON could not be parsed: ${error.message}`);",
    "  }",
    "}",
    "",
    "const LOOKER_TIMEOUT_MS = 60_000;",
    "",
    "function lookerHeaders(accessToken, extra = {}) {",
    "  return {",
    "    Accept: \"application/json\",",
    "    Authorization: `token ${accessToken}`,",
    "    ...extra,",
    "  };",
    "}",
    "",
    "async function httpJson(method, url, { headers = {}, body, timeoutMs = LOOKER_TIMEOUT_MS } = {}) {",
    "  const controller = new AbortController();",
    "  const timer = setTimeout(() => controller.abort(), timeoutMs);",
    "  try {",
    "    const response = await fetch(url, { method, headers, body, signal: controller.signal });",
    "    const text = await response.text();",
    "    if (!response.ok) {",
    "      throw new Error(`HTTP ${response.status} from ${url}: ${text || response.statusText}`);",
    "    }",
    "    if (!text) return null;",
    "    try {",
    "      return JSON.parse(text);",
    "    } catch (error) {",
    "      throw new Error(`Expected JSON from ${url}, got ${text.slice(0, 500)}`);",
    "    }",
    "  } finally {",
    "    clearTimeout(timer);",
    "  }",
    "}",
    "",
    "async function httpBytes(method, url, { headers = {}, timeoutMs = LOOKER_TIMEOUT_MS } = {}) {",
    "  const controller = new AbortController();",
    "  const timer = setTimeout(() => controller.abort(), timeoutMs);",
    "  try {",
    "    const response = await fetch(url, { method, headers, signal: controller.signal });",
    "    if (!response.ok) {",
    "      const text = await response.text();",
    "      throw new Error(`HTTP ${response.status} from ${url}: ${text || response.statusText}`);",
    "    }",
    "    return Buffer.from(await response.arrayBuffer());",
    "  } finally {",
    "    clearTimeout(timer);",
    "  }",
    "}",
    "",
    "async function loginToLooker(baseUrl, apiVersion, clientId, clientSecret) {",
    "  const body = new URLSearchParams({ client_id: clientId, client_secret: clientSecret });",
    "  const payload = await httpJson(\"POST\", `${baseUrl.replace(/\\/+$/, \"\")}/api/${apiVersion}/login`, {",
    "    headers: { \"Content-Type\": \"application/x-www-form-urlencoded\", Accept: \"application/json\" },",
    "    body: body.toString(),",
    "  });",
    "  if (!payload?.access_token) throw new Error(\"Looker login did not return an access token.\");",
    "  return String(payload.access_token);",
    "}",
    "",
    "async function getLook(baseUrl, apiVersion, accessToken, lookId) {",
    "  return httpJson(\"GET\", `${baseUrl.replace(/\\/+$/, \"\")}/api/${apiVersion}/looks/${encodeURIComponent(String(lookId))}`, {",
    "    headers: lookerHeaders(accessToken),",
    "  });",
    "}",
    "",
    "async function getQuery(baseUrl, apiVersion, accessToken, queryId) {",
    "  return httpJson(\"GET\", `${baseUrl.replace(/\\/+$/, \"\")}/api/${apiVersion}/queries/${encodeURIComponent(String(queryId))}`, {",
    "    headers: lookerHeaders(accessToken),",
    "  });",
    "}",
    "",
    "async function createExportQuery(baseUrl, apiVersion, accessToken, baseQuery, extraFilters = null) {",
    "  const mergedFilters = { ...(baseQuery.filters || {}) };",
    "  if (extraFilters) Object.assign(mergedFilters, extraFilters);",
    "  const payload = {",
    "    model: baseQuery.model,",
    "    view: baseQuery.view,",
    "    fields: baseQuery.fields,",
    "    filters: mergedFilters,",
    "    filter_expression: baseQuery.filter_expression,",
    "    sorts: baseQuery.sorts,",
    "    limit: \"-1\",",
    "    column_limit: baseQuery.column_limit,",
    "    total: baseQuery.total,",
    "    row_total: baseQuery.row_total,",
    "    subtotals: baseQuery.subtotals,",
    "    vis_config: baseQuery.vis_config,",
    "    filter_config: null,",
    "    query_timezone: baseQuery.query_timezone,",
    "    dynamic_fields: baseQuery.dynamic_fields,",
    "  };",
    "  const created = await httpJson(\"POST\", `${baseUrl.replace(/\\/+$/, \"\")}/api/${apiVersion}/queries`, {",
    "    headers: lookerHeaders(accessToken, { \"Content-Type\": \"application/json\" }),",
    "    body: JSON.stringify(payload),",
    "  });",
    "  if (!created?.id) throw new Error(\"Failed to create Looker export query.\");",
    "  return String(created.id);",
    "}",
    "",
    "function periodMonthValue(period) {",
    "  return String(period || \"\").replace(\"-\", \"/\");",
    "}",
    "",
    "function periodDateRangeValue(period) {",
    "  const year = Number(String(period || \"\").slice(0, 4));",
    "  const month = Number(String(period || \"\").slice(5, 7));",
    "  const lastDay = new Date(Date.UTC(year, month, 0)).getUTCDate();",
    "  return `${period}-01 to ${period}-${String(lastDay).padStart(2, \"0\")}`;",
    "}",
    "",
    "function buildPeriodFilterValue(period, mode) {",
    "  const normalized = String(mode || \"month\").trim().toLowerCase();",
    "  if ([\"month\", \"month_value\"].includes(normalized)) return periodMonthValue(period);",
    "  if ([\"date_range\", \"month_range\"].includes(normalized)) return periodDateRangeValue(period);",
    "  if (normalized === \"raw\") return String(period || \"\");",
    "  throw new Error(`Unsupported Looker period filter mode: ${mode}`);",
    "}",
    "",
    "function buildHistoryFilterValue(historyWindowDays) {",
    "  return `${Math.max(1, Number(historyWindowDays || 0))} day`;",
    "}",
    "",
    "async function createQueryTask(baseUrl, apiVersion, accessToken, queryId, resultFormat, forceProduction) {",
    "  const payload = { query_id: String(queryId), result_format: resultFormat, source: \"billing-workbook-n8n-cloud\" };",
    "  if (forceProduction) payload.force_production = true;",
    "  const task = await httpJson(\"POST\", `${baseUrl.replace(/\\/+$/, \"\")}/api/${apiVersion}/query_tasks`, {",
    "    headers: lookerHeaders(accessToken, { \"Content-Type\": \"application/json\" }),",
    "    body: JSON.stringify(payload),",
    "  });",
    "  if (!task?.id) throw new Error(`Failed to create Looker query task for query ${queryId}`);",
    "  return String(task.id);",
    "}",
    "",
    "async function waitForQueryTaskResults(baseUrl, apiVersion, accessToken, taskId, timeoutSeconds) {",
    "  const deadline = Date.now() + (Math.max(1, Number(timeoutSeconds || 600)) * 1000);",
    "  const url = `${baseUrl.replace(/\\/+$/, \"\")}/api/${apiVersion}/query_tasks/${encodeURIComponent(String(taskId))}/results`;",
    "  let transient404Count = 0;",
    "  while (Date.now() < deadline) {",
    "    const response = await fetch(url, { headers: { Authorization: `token ${accessToken}`, Accept: \"*/*\" } });",
    "    if (response.status === 202) {",
    "      await new Promise((resolve) => setTimeout(resolve, 2000));",
    "      continue;",
    "    }",
    "    if (response.status === 404) {",
    "      transient404Count += 1;",
    "      await new Promise((resolve) => setTimeout(resolve, Math.min(5000, (1 + transient404Count) * 1000)));",
    "      continue;",
    "    }",
    "    if (!response.ok) {",
    "      const detail = await response.text();",
    "      throw new Error(`HTTP ${response.status} from ${url}: ${detail || response.statusText}`);",
    "    }",
    "    return Buffer.from(await response.arrayBuffer());",
    "  }",
    "  throw new Error(`Timed out waiting for Looker query task ${taskId} after ${timeoutSeconds} seconds`);",
    "}",
    "",
    "async function fetchReportCsv(ctx, accessToken, spec) {",
    "  const look = await getLook(ctx.lookerBaseUrl, ctx.lookerApiVersion, accessToken, spec.lookId);",
    "  if (!look?.query_id) throw new Error(`Look ${spec.lookId} did not return a query_id`);",
    "  const baseQuery = await getQuery(ctx.lookerBaseUrl, ctx.lookerApiVersion, accessToken, look.query_id);",
    "  const sourceMetadata = {",
    "    lookId: String(spec.lookId),",
    "    reportName: spec.reportName,",
    "    fileName: spec.fileName,",
    "    resultFormat: \"csv\",",
    "    fetchedAt: new Date().toISOString(),",
    "    baseQueryId: String(look.query_id),",
    "    baseQueryLimit: baseQuery?.limit ?? null,",
    "    baseQueryColumnLimit: baseQuery?.column_limit ?? null,",
    "  };",
    "  let effectiveQueryId = String(look.query_id);",
    "  if (spec.periodFilterKey) {",
    "    const filterValue = buildPeriodFilterValue(ctx.period, spec.periodFilterMode);",
    "    effectiveQueryId = await createExportQuery(ctx.lookerBaseUrl, ctx.lookerApiVersion, accessToken, baseQuery, { [spec.periodFilterKey]: filterValue });",
    "    sourceMetadata.periodFilterKey = spec.periodFilterKey;",
    "    sourceMetadata.periodFilterMode = spec.periodFilterMode || \"month\";",
    "    sourceMetadata.periodFilterValue = filterValue;",
    "  } else if (spec.historyFilterKey && Number(spec.historyWindowDays || 0) > 0) {",
    "    const filterValue = buildHistoryFilterValue(spec.historyWindowDays);",
    "    effectiveQueryId = await createExportQuery(ctx.lookerBaseUrl, ctx.lookerApiVersion, accessToken, baseQuery, { [spec.historyFilterKey]: filterValue });",
    "    sourceMetadata.historyFilterKey = spec.historyFilterKey;",
    "    sourceMetadata.historyFilterValue = filterValue;",
    "  } else {",
    "    effectiveQueryId = await createExportQuery(ctx.lookerBaseUrl, ctx.lookerApiVersion, accessToken, baseQuery, null);",
    "  }",
    "  sourceMetadata.exportQueryLimit = \"-1\";",
    "  sourceMetadata.queryId = effectiveQueryId;",
    "  const taskId = await createQueryTask(ctx.lookerBaseUrl, ctx.lookerApiVersion, accessToken, effectiveQueryId, \"csv\", ctx.forceProduction);",
    "  sourceMetadata.queryTaskId = taskId;",
    "  const csvBytes = await waitForQueryTaskResults(ctx.lookerBaseUrl, ctx.lookerApiVersion, accessToken, taskId, spec.reportTimeout || 600);",
    "  sourceMetadata.byteCount = csvBytes.length;",
    "  const csvText = new TextDecoder(\"utf-8\").decode(csvBytes);",
    "  return { csvText, sourceMetadata };",
    "}",
    "",
    "function buildJsonBinary(fileName, jsonText) {",
    "  return {",
    "    data: Buffer.from(jsonText, \"utf8\").toString(\"base64\"),",
    "    fileName,",
    "    mimeType: \"application/json\",",
    "  };",
    "}",
    "",
    "function buildKeyParts(objectKey) {",
    "  const cleaned = String(objectKey || \"\").replace(/^\\/+|\\/+$/g, \"\");",
    "  const parts = cleaned.split(\"/\");",
    "  const fileName = parts.pop() || \"artifact.json\";",
    "  return { parentFolderKey: parts.join(\"/\"), fileName };",
    "}",
    "",
    runtimeSource,
    "",
    "if (!ctx.lookerClientId || ctx.lookerClientId === \"SET_LOOKER_CLIENT_ID\" || !ctx.lookerClientSecret || ctx.lookerClientSecret === \"SET_LOOKER_CLIENT_SECRET\") {",
    "  throw new Error(\"Set the Looker client ID and client secret in the Build Run Context node before running this workflow.\");",
    "}",
    "",
    "const accessToken = await loginToLooker(ctx.lookerBaseUrl, ctx.lookerApiVersion, ctx.lookerClientId, ctx.lookerClientSecret);",
    "const reportResults = [];",
    "for (const spec of ctx.reports || []) {",
    "  const entry = {",
    "    fileType: spec.fileType,",
    "    fileName: spec.fileName,",
    "    lookId: spec.lookId,",
    "    reportName: spec.reportName,",
    "  };",
    "  try {",
    "    const { csvText, sourceMetadata } = await fetchReportCsv(ctx, accessToken, spec);",
    "    const { workbook, result } = applyLookerCsvToWorkbook(workbookPayload, {",
    "      fileType: spec.fileType,",
    "      period: ctx.period,",
    "      csvText,",
    "    }, {",
    "      includeDetailRows: false,",
    "      savedAt: new Date().toISOString(),",
    "      runId: ctx.runId,",
    "      source: \"n8n-cloud\",",
    "    });",
    "    workbookPayload = workbook;",
    "    result.sourceMetadata = sourceMetadata;",
    "    entry.status = \"imported\";",
    "    entry.savedAt = workbook.savedAt || new Date().toISOString();",
    "    entry.warnings = result.warnings || [];",
    "    entry.stats = result.stats || {};",
    "    entry.changeSummary = result.changeSummary || {};",
    "    entry.sourceMetadata = sourceMetadata;",
    "    entry.sectionKeys = Object.keys(result.sections || {});",
    "    entry.byteCount = sourceMetadata.byteCount || 0;",
    "  } catch (error) {",
    "    entry.status = \"error\";",
    "    entry.error = error.message || String(error);",
    "    entry.warnings = [];",
    "  }",
    "  reportResults.push(entry);",
    "}",
    "const savedAt = new Date().toISOString();",
    "if (!workbookPayload.workspace || typeof workbookPayload.workspace !== \"object\") workbookPayload.workspace = {};",
    "if (!workbookPayload.workspace.label) workbookPayload.workspace.label = \"Veem Billing Workspace\";",
    "workbookPayload.savedAt = savedAt;",
    "const summary = {",
    "  ...normalizeCloudSyncSummary(reportResults),",
    "  configSource: \"embedded-cloud-workflow\",",
    "  period: ctx.period,",
    "  runId: ctx.runId,",
    "  baseUrl: ctx.lookerBaseUrl,",
    "  apiVersion: ctx.lookerApiVersion,",
    "  forceProduction: ctx.forceProduction,",
    "  source: \"n8n-cloud\",",
    "  savedAt,",
    "};",
    "const workbookJson = JSON.stringify(workbookPayload, null, 2);",
    "const summaryJson = JSON.stringify(summary, null, 2);",
    "const workbookKeyParts = buildKeyParts(ctx.workbookKey);",
    "const summaryKeyParts = buildKeyParts(ctx.summaryKey);",
    "const historyTimestamp = savedAt.replace(/[-:.TZ]/g, \"\").slice(0, 14);",
    "const historyParentFolderKey = String(ctx.workbookHistoryPrefix || \"\").replace(/^\\/+|\\/+$/g, \"\");",
    "const historyFileName = `current-workbook-${historyTimestamp}.json`;",
    "return [{",
    "  json: {",
    "    bucketName: ctx.bucketName,",
    "    workbookParentFolderKey: workbookKeyParts.parentFolderKey,",
    "    workbookFileName: workbookKeyParts.fileName,",
    "    summaryParentFolderKey: summaryKeyParts.parentFolderKey,",
    "    summaryFileName: summaryKeyParts.fileName,",
    "    workbookHistoryParentFolderKey: historyParentFolderKey,",
    "    workbookHistoryFileName: historyFileName,",
    "    savedAt,",
    "    runId: ctx.runId,",
    "    period: ctx.period,",
    "    hasErrors: summary.hasErrors,",
    "    errorCount: summary.errorCount,",
    "    importedCount: summary.importedCount,",
    "  },",
    "  binary: {",
    "    workbookFile: buildJsonBinary(workbookKeyParts.fileName, workbookJson),",
    "    workbookHistoryFile: buildJsonBinary(historyFileName, workbookJson),",
    "    summaryFile: buildJsonBinary(summaryKeyParts.fileName, summaryJson),",
    "  },",
    "}];",
  ].join("\n");
}

function buildWorkflow(config, runtimeSource) {
  const workbookKeyParts = splitS3Key(DEFAULT_WORKBOOK_KEY);
  const summaryKeyParts = splitS3Key(DEFAULT_SUMMARY_KEY);
  const workflow = {
    name: "Billing Workbook Looker Cloud Sync",
    active: false,
    isArchived: false,
    nodes: [
      {
        parameters: {},
        id: "manual-trigger",
        name: "Manual Trigger",
        type: "n8n-nodes-base.manualTrigger",
        typeVersion: 1,
        position: [240, 260],
      },
      {
        parameters: {
          rule: {
            interval: [
              {
                field: "cronExpression",
                expression: "=0 7 * * *",
              },
            ],
          },
        },
        id: "daily-schedule",
        name: "Daily Schedule",
        type: "n8n-nodes-base.scheduleTrigger",
        typeVersion: 1.2,
        position: [240, 460],
      },
      {
        parameters: {
          jsCode: buildContextCode(config),
        },
        id: "build-run-context",
        name: "Build Run Context",
        type: "n8n-nodes-base.code",
        typeVersion: 2,
        position: [540, 360],
      },
      {
        parameters: {
          resource: "file",
          operation: "download",
          bucketName: "={{ $json.bucketName }}",
          fileKey: "={{ $json.workbookKey }}",
          binaryPropertyName: "currentWorkbook",
        },
        id: "download-current-workbook",
        name: "Download Current Workbook",
        type: "n8n-nodes-base.awsS3",
        typeVersion: 1,
        position: [860, 360],
      },
      {
        parameters: {
          jsCode: buildSyncCode(runtimeSource),
        },
        id: "run-cloud-sync",
        name: "Run Cloud Looker Sync",
        type: "n8n-nodes-base.code",
        typeVersion: 2,
        position: [1180, 360],
      },
      {
        parameters: {
          resource: "file",
          operation: "upload",
          bucketName: "={{ $json.bucketName }}",
          fileName: "={{ $json.workbookFileName }}",
          binaryData: true,
          binaryPropertyName: "workbookFile",
          additionalFields: {
            parentFolderKey: "={{ $json.workbookParentFolderKey }}",
          },
        },
        id: "upload-current-workbook",
        name: "Upload Current Workbook",
        type: "n8n-nodes-base.awsS3",
        typeVersion: 1,
        position: [1520, 220],
      },
      {
        parameters: {
          resource: "file",
          operation: "upload",
          bucketName: "={{ $json.bucketName }}",
          fileName: "={{ $json.workbookHistoryFileName }}",
          binaryData: true,
          binaryPropertyName: "workbookHistoryFile",
          additionalFields: {
            parentFolderKey: "={{ $json.workbookHistoryParentFolderKey }}",
          },
        },
        id: "upload-workbook-history",
        name: "Upload Workbook History",
        type: "n8n-nodes-base.awsS3",
        typeVersion: 1,
        position: [1520, 360],
      },
      {
        parameters: {
          resource: "file",
          operation: "upload",
          bucketName: "={{ $json.bucketName }}",
          fileName: "={{ $json.summaryFileName }}",
          binaryData: true,
          binaryPropertyName: "summaryFile",
          additionalFields: {
            parentFolderKey: "={{ $json.summaryParentFolderKey }}",
          },
        },
        id: "upload-sync-summary",
        name: "Upload Sync Summary",
        type: "n8n-nodes-base.awsS3",
        typeVersion: 1,
        position: [1520, 500],
      },
    ],
    connections: {
      "Manual Trigger": {
        main: [[{ node: "Build Run Context", type: "main", index: 0 }]],
      },
      "Daily Schedule": {
        main: [[{ node: "Build Run Context", type: "main", index: 0 }]],
      },
      "Build Run Context": {
        main: [[{ node: "Download Current Workbook", type: "main", index: 0 }]],
      },
      "Download Current Workbook": {
        main: [[{ node: "Run Cloud Looker Sync", type: "main", index: 0 }]],
      },
      "Run Cloud Looker Sync": {
        main: [[
          { node: "Upload Current Workbook", type: "main", index: 0 },
          { node: "Upload Workbook History", type: "main", index: 0 },
          { node: "Upload Sync Summary", type: "main", index: 0 },
        ]],
      },
    },
    settings: {
      executionOrder: "v1",
      callerPolicy: "workflowsFromSameOwner",
      availableInMCP: false,
    },
    pinData: {},
    meta: {
      templateCredsSetupCompleted: false,
    },
    versionId: "cloud-looker-sync-template",
    tags: [],
  };

  return workflow;
}

function main() {
  const config = JSON.parse(fs.readFileSync(CONFIG_PATH, "utf8"));
  const runtimeSource = stripExports(fs.readFileSync(RUNTIME_PATH, "utf8"));
  const workflowPayload = buildWorkflow(config, runtimeSource);
  fs.writeFileSync(OUTPUT_PATH, `${JSON.stringify(workflowPayload, null, 2)}\n`, "utf8");
  console.log(`Wrote ${OUTPUT_PATH}`);
}

main();
